### ISSUE TITLE
Failed Units: 1   systemd-tmpfiles-setup.service

### ISSUE THREAD

**Issue by Knight1** [coreos/bugs#1763]
# Issue Report #

Container Linux by CoreOS beta (1248.4.0)
Failed Units: 1
  systemd-tmpfiles-setup.service

### CoreOS Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1248.4.0
VERSION_ID=1248.4.0
BUILD_ID=2017-01-10-0554
PRETTY_NAME="Container Linux by CoreOS 1248.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Actual Behavior ###

```
core@service-failure-test ~ $ journalctl -xe
Jan 15 21:22:32 service-failure-test systemd-tmpfiles[1560]: Failed to copy files to /var/lib/nfs/etab: No such file or directory
Jan 15 21:22:32 service-failure-test systemd-tmpfiles[1560]: Failed to copy files to /var/lib/nfs/rmtab: No such file or directory
Jan 15 21:22:32 service-failure-test systemd-tmpfiles[1560]: Failed to copy files to /var/lib/nfs/state: No such file or directory
Jan 15 21:22:32 service-failure-test systemd-tmpfiles[1560]: Failed to copy files to /var/lib/nfs/xtab: No such file or directory
Jan 15 21:22:32 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 21:22:32 service-failure-test systemd[1]: Failed to start Create Volatile Files and Directories.
-- Subject: Unit systemd-tmpfiles-setup.service has failed

core@service-failure-test ~ $ systemctl status systemd-tmpfiles-setup.service
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
   Loaded: loaded (/usr/lib/systemd/system/systemd-tmpfiles-setup.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2017-01-15 21:22:32 UTC; 2min 37s ago
     Docs: man:tmpfiles.d(5)
           man:systemd-tmpfiles(8)
 Main PID: 1560 (code=exited, status=1/FAILURE)

Jan 15 21:22:32 service-failure-test systemd[1]: Starting Create Volatile Files and Directories...
Jan 15 21:22:32 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 21:22:32 service-failure-test systemd[1]: Failed to start Create Volatile Files and Directories.
Jan 15 21:22:32 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Unit entered failed state.
Jan 15 21:22:32 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Failed with result 'exit-code'.
```

### Reproduction Steps ###

  1. installing CoreOS beta (1235.2.0) on packet.net 
  2. update_engine_client -update
```
Broadcast message from locksmithd at 2017-01-15 21:15:04.929281 +0000 UTC:
System reboot in 5 minutes!

LAST_CHECKED_TIME=1484514809
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=0.0.0.0
NEW_SIZE=206162545
I0115 21:15:05.419867  2635 update_engine_client.cc:194] Update succeeded -- reboot needed.
core@service-failure-test ~ $ reboot
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

ARMv8 on bare metal 96-core server at packet.net

### Desired Feature ###

No error message 😅

### Other Information ###

Thanks for any help!

**Comment by glevand** [comment]
I found this:
```
# egrep etab /usr/lib/tmpfiles.d/nfs-utils.conf
C /var/lib/nfs/etab     -       -       -       -       /usr/lib/nfs/etab

# ls -l /var/lib/nfs/etab /usr/lib/nfs
ls: cannot access '/usr/lib/nfs': No such file or directory
-rw-r--r-- 1 root root 0 Dec 14 23:19 /var/lib/nfs/etab
```
I'll look at it some more tomorrow.

**Comment by vielmetti** [comment]
This commit by @dm0- looks relevant 

https://github.com/coreos/coreos-overlay/commit/585e9070f2c166750f78418a7c246f2accf27cf1

**Comment by vielmetti** [comment]
and this PR looks relevant as well https://github.com/coreos/coreos-overlay/pull/2284

**Comment by glevand** [comment]
Should be fixed by https://github.com/coreos/coreos-overlay/commit/2bb3577448cbbaa6be83a47f39c8a6162d0a2fa1.

**Comment by Knight1** [comment]
Hi,

upgraded to 1248.4.0 and the bug still exists and the errors in the logs are the same.

```
core@service-failure-test ~ $ systemctl status systemd-tmpfiles-setup.service
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
   Loaded: loaded (/usr/lib/systemd/system/systemd-tmpfiles-setup.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-01-27 20:59:53 UTC; 19min ago
     Docs: man:tmpfiles.d(5)
           man:systemd-tmpfiles(8)
 Main PID: 1510 (code=exited, status=1/FAILURE)

Jan 27 20:59:53 service-failure-test systemd[1]: Starting Create Volatile Files and Directories...
Jan 27 20:59:53 service-failure-test systemd-tmpfiles[1510]: Failed to copy files to /var/lib/nfs/etab: No such file or directory
Jan 27 20:59:53 service-failure-test systemd-tmpfiles[1510]: Failed to copy files to /var/lib/nfs/rmtab: No such file or directory
Jan 27 20:59:53 service-failure-test systemd-tmpfiles[1510]: Failed to copy files to /var/lib/nfs/state: No such file or directory
Jan 27 20:59:53 service-failure-test systemd-tmpfiles[1510]: Failed to copy files to /var/lib/nfs/xtab: No such file or directory
Jan 27 20:59:53 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 20:59:53 service-failure-test systemd[1]: Failed to start Create Volatile Files and Directories.
Jan 27 20:59:53 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Unit entered failed state.
Jan 27 20:59:53 service-failure-test systemd[1]: systemd-tmpfiles-setup.service: Failed with result 'exit-code'.
core@service-failure-test ~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1248.4.0
VERSION_ID=1248.4.0
BUILD_ID=2017-01-10-0554
PRETTY_NAME="Container Linux by CoreOS 1248.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

Thanks

**Comment by crawford** [comment]
@Knight1 the fix made it into [1298.1.0](https://coreos.com/releases/#1298.1.0).

**Comment by vielmetti** [comment]
Any chance this fix can be backported into stable? I'm seeing this:

```
Container Linux by CoreOS stable (1235.9.0)
Failed Units: 1
  systemd-tmpfiles-setup.service
```

on the same machine type @Knight1 is looking at.

**Comment by dm0-** [comment]
Stable is currently at 1298.5.0 (https://stable.release.core-os.net/amd64-usr/current/version.txt), so it should be fixed in all channels.

**Comment by vielmetti** [comment]
Hm. arm64 is at 1235.9.0 (https://stable.release.core-os.net/arm64-usr/current/version.txt) if I read it right, so it's lagging behind stable for amd64?

**Comment by dm0-** [comment]
Oh, I don't think the arm64 stable channel is supported or officially exists (i.e. there is no auto-update group for it), but some releases accidentally got published for it there.  A new stable version should go out around Wednesday, and I could release that for arm64 stable, but you should probably switch any ARM systems to the beta channel if you want to get automatic updates.

**Comment by vielmetti** [comment]
Thanks @dm0- that explains the situation.
