### ISSUE TITLE
Error with SSL volumes in /usr/lib/coreos/flannel-wrapper

### ISSUE THREAD

**Issue by magna-z** [coreos/bugs#2039]
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.5.0
VERSION_ID=1409.5.0
BUILD_ID=2017-06-22-2222
PRETTY_NAME="Container Linux by CoreOS 1409.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Actual Behavior ###
In wrapper-script "/usr/lib/coreos/flannel-wrapper" on line 71 volume parameter "etc-ssl-certs" set source path as "/usr/share/ca-certificates", but in mount parameter for volume "etc-ssl-certs" using path "/etc/ssl/certs".
```
$ tail -n 20 /usr/lib/coreos/flannel-wrapper
RKT_STAGE1_ARG="${RKT_STAGE1_ARG:---stage1-from-dir=stage1-fly.aci}"
set -x
exec ${RKT} ${RKT_GLOBAL_ARGS} \
	run ${RKT_RUN_ARGS} \
	--net=host \
	--volume run-flannel,kind=host,source=/run/flannel,readOnly=false \
	--volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true \
	--volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true \
	--volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true \
	--volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true \
	--mount volume=run-flannel,target=/run/flannel \
	--mount volume=etc-ssl-certs,target=/etc/ssl/certs \
	--mount volume=usr-share-certs,target=/usr/share/ca-certificates \
	--mount volume=etc-hosts,target=/etc/hosts  \
	--mount volume=etc-resolv,target=/etc/resolv.conf \
	--inherit-env \
	${RKT_STAGE1_ARG} \
	${FLANNEL_IMAGE} \
		${FLANNEL_IMAGE_ARGS} \
		-- "$@"
```

**Comment by dm0-** [comment]
This was fixed in coreos/coreos-overlay#2571.

**Comment by maxkondr** [comment]
@dm0- 

I am testing CoreOS 
```
cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```


And the issue is still there

**Comment by bgilbert** [comment]
@maxkondr This is fixed in Container Linux [1423.0.0](https://coreos.com/releases/#1423.0.0).  The fix is included in current alpha and beta releases, and should be in the next major stable release.
