### ISSUE TITLE
container oom would cause docker ps hang

### ISSUE THREAD

**Issue by zq-david-wang** [coreos/bugs#2320]
# Issue Report #

## Bug ##
Docker fail to create/terminate containers after several oom.
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
K8s1.6 cluster on CoreOS installed on bare-metal.

### Actual Behavior ###
After several OOM events, docker ps would hang, and no container could be created or terminated
### Reproduction Steps ###
  1.  Using kubernetes to create a replicaset with memory limit lower than the container needed. 
  2. Keep running the replicaset, it would eventually happened that docker on the running node would run into some "hang" state.

I use docker-stress to trigger OOM, as in following k8s resource file:
oom-replica.yml
```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    replicaset: oomtest
  name: oomtest
  namespace: k8sft
spec:
  replicas: 1
  selector:
    matchLabels:
      replicaset: oomtest
  template:
    metadata:
      labels:
        replicaset: oomtest
    spec:
      containers:
      - args:
        - -m
        - "10"
        - --vm-bytes
        - 128M
        - --timeout
        - 60s
        - --vm-keep
        image: progrium/stress
        imagePullPolicy: Always
        name: oom-stress
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
``` 
kubectl create -f oom-replica.yml

### Other Information ###

When docker ps hang, runc show that some containers are in create state
```
$ sudo runc list | grep -v running
ID                                                                 PID         STATUS      BUNDLE                                                                                       CREATED
21921578a2264003af4ce1e90265cc778160d9ec6f49237539da1067a70d4a77   83662       created     /run/docker/libcontainerd/21921578a2264003af4ce1e90265cc778160d9ec6f49237539da1067a70d4a77   2018-01-19T03:15:04.681450044Z
39aa585e8664bd24009c906a32334f0ae04f16fcf950a56b7393697a3524990c   59079       created     /run/docker/libcontainerd/39aa585e8664bd24009c906a32334f0ae04f16fcf950a56b7393697a3524990c   2018-01-19T02:53:03.984527124Z
49b358c587079171bf7d582921572a5878d3e38acdb8f53f148f1e47d333fe09   59131       created     /run/docker/libcontainerd/49b358c587079171bf7d582921572a5878d3e38acdb8f53f148f1e47d333fe09   2018-01-19T02:53:04.067925311Z
87ab156bc334456b76a0a9ffbf29ed38d5c377ce0ce47247c2fae15dec6b1a70   62723       created     /run/docker/libcontainerd/87ab156bc334456b76a0a9ffbf29ed38d5c377ce0ce47247c2fae15dec6b1a70   2018-01-19T02:59:04.679274528Z
9412b399dfa56921eec56371bb9d5d0cfcadcd8494dede1a6df92f58a63bac31   0           stopped     /run/docker/libcontainerd/9412b399dfa56921eec56371bb9d5d0cfcadcd8494dede1a6df92f58a63bac31   2018-01-19T02:52:59.763999091Z
a22c7fb38d1029682768b3106945ff4b260341831eff7e374dadcb0eacdc8e30   0           stopped     /run/docker/libcontainerd/a22c7fb38d1029682768b3106945ff4b260341831eff7e374dadcb0eacdc8e30   2018-01-18T08:50:56.261317199Z
```
ps would show that the process as following
```
$ ps aux | grep 83662
root      83662  0.0  0.0 125068  7612 ?        Ssl  03:15   0:00 /proc/self/exe init
$ sudo cat /proc/83662/stack
[<ffffffffa1220b70>] pipe_wait+0x70/0xc0
[<ffffffffa1220bf1>] wait_for_partner+0x31/0x60
[<ffffffffa12217ec>] fifo_open+0x16c/0x2c0
[<ffffffffa1213f04>] do_dentry_open+0x1e4/0x300
[<ffffffffa1215451>] vfs_open+0x51/0x80
[<ffffffffa122737e>] path_openat+0x2be/0x16f0
[<ffffffffa1229ab9>] do_filp_open+0x99/0x110
[<ffffffffa1215875>] do_sys_open+0x125/0x210
[<ffffffffa1215994>] SyS_openat+0x14/0x20
[<ffffffffa1003afa>] do_syscall_64+0x5a/0x160
[<ffffffffa16131e7>] entry_SYSCALL64_slow_path+0x25/0x25
[<ffffffffffffffff>] 0xffffffffffffffff
$ sudo ls -l /proc/83662/exe     
lrwxrwxrwx. 1 root root 0 Jan 19 03:15 /proc/83662/exe -> /run/torcx/unpack/docker/bin/runc
```
strace show that the process is reading a pipe
```
$ sudo strace -p 83662
Process 83662 attached
openat(4, "exec.fifo", O_WRONLY|O_CLOEXEC
```
According to runc, this means that the container is waiting for "runc start"

And sometimes, if I caught the "docker ps hang" in time, and execute "runc start" on the created container, docker would recover to normal. (If it is tool late and several container is in created state, "runc start" would not help)

I suspect that there is some race condition between dockerd and runc, and I instrument "do_sys_open" to monitor the "exec.fifo" file via kprobe(bcc). Strange thing is after the instrument the "docker ps hang" could not be reproduced.

**Comment by zq-david-wang** [comment]
Actually I am running a modified version of k8s1.6, which would not "CrashBackOff" for failed pod.
Instead, it would restart failed container immediately.

**Comment by brat002** [comment]
I also have such problem. OOM event sometimes hangs docker for several minutes.

**Comment by zq-david-wang** [comment]
https://github.com/containerd/containerd/issues/1882

I think the issue mentioned in upper link is the exact the same. The fix is in containerd 1.0.2, when would this fix merged into CoreOS docker?

**Comment by ajeddeloh** [comment]
Container Linux's containerd version tracks its our docker version. Alpha typically tracks the docker edge releases which as of this moment use containerd 1.0.1 (see [the docker release notes](https://docs.docker.com/release-notes/docker-ce/#18020-ce-2018-02-07)). Once docker bumps it's containerd version to 1.0.2 it will make it's way into alpha.

**Comment by brat002** [comment]
The problem wasn't solved.
```
# time docker exec -it be11451115d0 ls
app.jar  etc      media    root     srv      usr
bin      home     mnt      run      sys      var
dev      lib      proc     sbin     tmp

real	0m10.738s
user	0m0.027s
sys	0m0.021s
```
Docker commands are almost unusable in case of OOM presence.

**Comment by zq-david-wang** [comment]
Close this issue since docker-18.03.0-ce has containerd bumped to 1.0.2.  And my clusters have run on containerd 1.0.2 for more than two weeks without getting a hang.
